---
title: "My First Flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
# load library
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)

```

```{r}

set.seed(1)

data(nyc_airbnb)
nyc_airbnb = 
  nyc_airbnb %>% 
  # get a 5-star scale rating from the original out of 10 scale rating 
  mutate(rating = review_scores_location / 2) %>%
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>%
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)  %>% 
  # give a sample size of 5000 from this dataset
  sample_n(5000)

```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

nyc_airbnb %>%
  mutate(text_label = str_c("Price: $", price, '\nRating: ', rating)) %>% 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = 0.5)

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
common_neighborhoods =
  nyc_airbnb %>% 
  # count the # of occurence by neighbourhodd and sort it from the largest to the smallest
  count(neighbourhood, sort = TRUE) %>% 
  # display only the 8 largest neighbourhood
  top_n(8) %>% 
  # keep only neighbourhood variable
  select(neighbourhood)

# kept only the data for the above 8 neighbourhoods
inner_join(nyc_airbnb, common_neighborhoods, by = "neighbourhood") %>% 
  # reorder the level of neighbourhood and price
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box",
          colors = "Set2")
```

### Chart C

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar")
```

